/**
 * Recalculates Profit/Loss = Chips - Line Amount whenever either cell is edited.
 *
 * Works with multiple header rows in the same sheet (e.g. separate
 * positive and negative player tables generated by the Excel filter).
 *
 * Install: Extensions → Apps Script → paste this → Save (Ctrl+S).
 * No trigger setup needed — Google runs "onEdit" automatically on every edit.
 */
function onEdit(e) {
  const sheet = e.range.getSheet();
  const editedRow = e.range.getRow();
  const editedCol = e.range.getColumn();

  const sections = getHeaderSections(sheet);
  if (sections.length === 0) return;

  // Find the nearest header row at or above the edited row
  let section = null;
  for (const s of sections) {
    if (s.headerRow <= editedRow) section = s;
    else break;
  }

  // Ignore edits on a header row itself or outside any known section
  if (!section || editedRow === section.headerRow) return;

  // Only act on edits in "Chips" or "Line Amount" columns
  if (editedCol !== section.chipsCol && editedCol !== section.lineAmountCol) return;

  const chips = Number(sheet.getRange(editedRow, section.chipsCol).getValue()) || 0;
  const line  = Number(sheet.getRange(editedRow, section.lineAmountCol).getValue()) || 0;

  sheet.getRange(editedRow, section.profitLossCol).setValue(Math.trunc(chips - line));
}

/**
 * Scans every row of the sheet for a row that contains all three headers.
 * Returns an array of section descriptors sorted by row number.
 */
function getHeaderSections(sheet) {
  const lastRow = sheet.getLastRow();
  const lastCol = sheet.getLastColumn();
  if (lastRow === 0 || lastCol === 0) return [];

  const data = sheet.getRange(1, 1, lastRow, lastCol).getValues();
  const sections = [];

  for (let r = 0; r < data.length; r++) {
    let chipsCol = -1, lineAmountCol = -1, profitLossCol = -1;

    for (let c = 0; c < data[r].length; c++) {
      const cell = String(data[r][c]).trim();
      if (cell === 'Chips')        chipsCol        = c + 1;
      if (cell === 'Line Amount')  lineAmountCol   = c + 1;
      if (cell === 'Profit/Loss')  profitLossCol   = c + 1;
    }

    if (chipsCol !== -1 && lineAmountCol !== -1 && profitLossCol !== -1) {
      sections.push({ headerRow: r + 1, chipsCol, lineAmountCol, profitLossCol });
    }
  }

  return sections;
}
